### ISSUE TITLE
MS/MS spectrum

### ISSUE THREAD

**Issue by BenSamy2020** [coongroup/IPSA#5]
Greetings,

Thank you for providing this open-source tool. 
By any chance will your tool be able to mirror two MS/MS spectra from 2 independent .raw file or .mgf files?

I would like to compare the fragment ion spectrum of a synthetic peptide and fragment ion spectrum identified experimentally.

Regards
Ben.

**Comment by dbrademan** [comment]
Hi Ben,

While mirror plots aren't currently featured in IPSA, it looks like ProteomicsDB and the Kuster lab have reimplemented IPSA into something that might address your needs. The tool is called the Universal Spectrum Explorer. There are likely other tools out there that can also make mirror plots, but USE is the first one that came to my mind.

Here's a link to their bioRxiv manuscript:
[https://www.biorxiv.org/content/10.1101/2020.09.08.287557v1.full.pdf](https://www.biorxiv.org/content/10.1101/2020.09.08.287557v1.full.pdf)

**Comment by BenSamy2020** [comment]
Greetings,

Thanks mate, the tool is extremely useful.
